### ISSUE TITLE
Need to show wallet error if there are no result in body

### ISSUE THREAD

**Issue by anronin** [libra-ventures/monero#9]
Right now if we misconfig `monero-wallet-rpc` for example didn't specify `--wallet-dir` or `--wallet-file` flags, we can still get 200 status but without `result` in the response body, instead were will be `error message`. So my suggest is in the case of result absence return an error with a message, wdyt?

**Comment by anronin** [comment]
we can modify `Wallet.Parser.parse` something like this
```elixir
def parse({:ok, %{body: body}}, config) do
  case config[:json_codec].decode!(body)["result"] do
    nil -> {:error, config[:json_codec].decode!(body)["error"]}
    result -> {:ok, result}
  end
end
```
and return this `{:error, %{"code" => -13, "message" => "No wallet file"}}` instead of `{:ok, nil}`

**Comment by lessless** [comment]
That makes sense. I'll take a look ASAP. Attach actual response next time,
please - it will help to have bigger picture.

On Sep 20, 2017 17:14, "Andrey N. Ronin" <notifications@github.com> wrote:

we can modify to Wallet.Parser.parse something like this

def parse({:ok, %{body: body}}, config) do
  case config[:json_codec].decode!(body)["result"] do
    nil -> {:error, config[:json_codec].decode!(body)["error"]}
    result -> {:ok, result}
  endend

and return this {:error, %{"code" => -13, "message" => "No wallet file"}}
instead of {:ok, nil}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/libra-ventures/monero/issues/9#issuecomment-330794179>,
or mute the thread

**Comment by lessless** [comment]
@anronin  looks like this will work - http://www.jsonrpc.org/specification#error_object
according to the spec `error` field is required to be present during error and only error. Do you mind a PR? 
Including daemon parser as well ;)

**Comment by anronin** [comment]
nice! sure, will be done asap
